import pandas as pd
import numpy as np

df = pd.read_csv("data/raw/prices.csv")

print("="*60)
print("SHAPE:", df.shape)
print("="*60)
print("\nFIRST 10 ROWS:")
print(df.head(10))
print("\n" + "="*60)
print("DATA TYPES:")
print(df.dtypes)
print("\n" + "="*60)
print("MISSING VALUES:")
print(df.isnull().sum())
print("\n" + "="*60)
print("STATISTICAL SUMMARY:")
print(df.describe())
print("\n" + "="*60)
print("VALUE COUNTS FOR 'MARKET':")
print(df['market'].value_counts(dropna=False))
print("\n" + "="*60)
print("VALUE COUNTS FOR 'COMMODITY':")
print(df['commodity'].value_counts(dropna=False))
print("\n" + "="*60)
print("UNIQUE DATES (first 20):")
print(df['date'].unique()[:20])
print("\n" + "="*60)
print("PRICE RANGE:")
print(f"Min: {df['price'].min()}, Max: {df['price'].max()}")
print("\n" + "="*60)
print("INVALID DATES (non-parseable):")
invalid_dates = df[df['date'].str.contains('-14-|-15-|-16-|-17-|-18-|-19-|-20-', regex=True, na=False)]
print(f"Count: {len(invalid_dates)}")
print(invalid_dates[['id', 'date', 'price']].head(10))
